### ISSUE TITLE
 Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by vvijayarajan** [OfficeDev/Office-Addin-TaskPane-JS#117]
Hello,

I am unable to create a project and getting following error

Unable to download project zip file for "https://github.com/OfficeDev/Office-Addin-TaskPane-JS/archive/yo-office.zip".
Error: unable to get local issuer certificate.

I tried creating a plain vanilla angular project and it works -  Please advise on missing configuration

![image](https://user-images.githubusercontent.com/131210228/232912890-f5f3a7f4-a5e6-41a1-8206-ba5a7a7a339c.png)

**Comment by millerds** [comment]
I don't think using the angular tools to create an angular project use the web in the same our plug-in does.  Are you able to access https://github.com/OfficeDev/Office-Addin-TaskPane-JS/archive/yo-office.zip directly from your browser on the same machine?

**Comment by vvijayarajan** [comment]
Yes I can access and download zip file via browser.

Thanks
Vivek Vijayarajan

**Comment by millerds** [comment]
Are you running 'yo office' behind a firewall or network that has special cert requirements for internet access?  I'm not an expert, but it looks like the code accessing that web location (a module called axios) needs a cert specific to your environment.  Since you can download the zip file you can extract it and run the convertToSingleHost.js script with the Office host you want as an argument to the script.

**Comment by vvijayarajan** [comment]
Thanks for your response – my machine is behind ZScalar Internet security.
Do you have any example on how to configure a certificate to make this work?

Thanks
Vivek Vijayarajan

**Comment by vvijayarajan** [comment]
My Issue got resolved by 

1.Setting CA Certificate 
2.Defining Environment Variable


Steps

a)Get your CA Root Certificate in .pem format
	npm config set cafile <Path to Certificate>/RootCertificate.pem
b)System Variable "NODE_EXTRA_CA_CERTS" "C:\<Path to Certificate>\RootCertificate.pem"
